### ISSUE TITLE
Error compiling patched Plumed 2.5.3 (static) with MPI(openmpi3)

### ISSUE THREAD

**Issue by max3925vats** [seanmarks/indus#2]
When trying to compile (with openmpi3) a static Plumed 2.5.3 with INDUS patched I get the following error: 

make[6]: Entering directory `<home_directory>/plumed-2.5.3/src/orderparameters'
compiling  MpiData.cpp
In file included from MpiCommunicator.h:79:0,
                 from MpiData.h:61,
                 from MpiData.cpp:1:
/usr/include/openmpi3-x86_64/mpi.h:328:33: **error**: conflicting declaration ‘typedef struct ompi_datatype_t* MPI_Datatype’
 typedef struct ompi_datatype_t ***MPI_Datatype;**
                                 
In file included from MpiData.h:13:0,
                 from MpiData.cpp:1:
MpiDatatype.h:30:7: **error**: ‘class MPI_Datatype’ has a previous declaration as ‘class MPI_Datatype’
 class **MPI_Datatype** {};
       
In file included from MpiCommunicator.h:79:0,
                 from MpiData.h:61,
                 from MpiData.cpp:1:
/usr/include/openmpi3-x86_64/mpi.h:333:27: **error**: conflicting declaration ‘typedef struct ompi_op_t* MPI_Op’
 typedef struct ompi_op_t ***MPI_Op**;
                           
In file included from MpiDatatype.h:24:0,
                 from MpiData.h:13,
                 from MpiData.cpp:1:
MpiOp.h:21:7: **error**: ‘class MPI_Op’ has a previous declaration as ‘class MPI_Op’
 class **MPI_Op {}**;
       
In file included from MpiCommunicator.h:79:0,
                 from MpiData.h:61,
                 from MpiData.cpp:1:
/usr/include/openmpi3-x86_64/mpi.h:394:71: **error**: conflicting declaration ‘typedef void MPI_User_function(void*, void*, int*, class MPI_Datatype*)’
 **typedef void (MPI_User_function)(void *, void *, int *, MPI_Datatype *);**
                                                                       
In file included from MpiDatatype.h:24:0,
                 from MpiData.h:13,
                 from MpiData.cpp:1:
MpiOp.h:22:7: **error**: ‘class MPI_User_function’ has a previous declaration as ‘class MPI_User_function’
 **class MPI_User_function {};**
       
In file included from MpiCommunicator.h:79:0,
                 from MpiData.h:61,
                 from MpiData.cpp:1:
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/datatype.h: In constructor ‘MPI::Datatype::Datatype()’:
/usr/include/openmpi3-x86_64/mpi.h:311:73: **error**: no matching function for call to ‘MPI_Datatype::MPI_Datatype(void*)’
 **#define OMPI_PREDEFINED_GLOBAL(type, global) ((type) ((void *) &(global)))**
                                                                         
/usr/include/openmpi3-x86_64/mpi.h:1041:27: **note**: in expansion of macro ‘OMPI_PREDEFINED_GLOBAL’
 **#define MPI_DATATYPE_NULL OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_datatype_null)**
                           
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/datatype.h:69:36: **note**: in expansion of macro ‘MPI_DATATYPE_NULL’
   **inline Datatype() : mpi_datatype(MPI_DATATYPE_NULL) { }**
                                    
/usr/include/openmpi3-x86_64/mpi.h:311:73: **note**: candidates are:
 **#define OMPI_PREDEFINED_GLOBAL(type, global) ((type) ((void *) &(global)))**
                                                                         
/usr/include/openmpi3-x86_64/mpi.h:1041:27: **note**: in expansion of macro ‘OMPI_PREDEFINED_GLOBAL’
 **#define MPI_DATATYPE_NULL OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_datatype_null)**
                           
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/datatype.h:69:36: **note**: in expansion of macro ‘MPI_DATATYPE_NULL’
   **inline Datatype() : mpi_datatype(MPI_DATATYPE_NULL) { }**
                                    
In file included from MpiData.h:13:0,
                 from MpiData.cpp:1:
MpiDatatype.h:30:7: **note**: constexpr MPI_Datatype::MPI_Datatype()
 **class MPI_Datatype {};**
       
MpiDatatype.h:30:7: **note**:   candidate expects 0 arguments, 1 provided
MpiDatatype.h:30:7: **note**: constexpr MPI_Datatype::MPI_Datatype(const MPI_Datatype&)
MpiDatatype.h:30:7: **note**:   no known conversion for argument 1 from ‘void*’ to ‘const MPI_Datatype&’
MpiDatatype.h:30:7: **note**: constexpr MPI_Datatype::MPI_Datatype(MPI_Datatype&&)
MpiDatatype.h:30:7: **note**:   no known conversion for argument 1 from ‘void*’ to ‘MPI_Datatype&&’
In file included from /usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/mpicxx.h:193:0,
                 from /usr/include/openmpi3-x86_64/mpi.h:2684,
                 from MpiCommunicator.h:79,
                 from MpiData.h:61,
                 from MpiData.cpp:1:
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/datatype.h: In member function ‘bool MPI::Datatype::operator==(const MPI::Datatype&) const’:
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/datatype.h:81:35: **error**: no match for ‘operator==’ (operand types are ‘const MPI_Datatype’ and ‘const MPI_Datatype’)
     **{ return (bool) (mpi_datatype == a.mpi_datatype); }**
                                   
In file included from MpiCommunicator.h:79:0,
                 from MpiData.h:61,
                 from MpiData.cpp:1:
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/op_inln.h: In constructor ‘MPI::Op::Op()’:
/usr/include/openmpi3-x86_64/mpi.h:311:73: **error**: no matching function for call to ‘MPI_Op::MPI_Op(void*)’
 **#define OMPI_PREDEFINED_GLOBAL(type, global) ((type) ((void *) &(global)))**
                                                                         
/usr/include/openmpi3-x86_64/mpi.h:745:21: **note**: in expansion of macro ‘OMPI_PREDEFINED_GLOBAL’
 **#define MPI_OP_NULL OMPI_PREDEFINED_GLOBAL(MPI_Op, ompi_mpi_op_null)**
                     
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:66:24: **note**: in expansion of macro ‘MPI_OP_NULL’
 **MPI::Op::Op() : mpi_op(MPI_OP_NULL) { }**
                        
/usr/include/openmpi3-x86_64/mpi.h:311:73: **note**: candidates are:
 **#define OMPI_PREDEFINED_GLOBAL(type, global) ((type) ((void *) &(global)))**
                                                                         
/usr/include/openmpi3-x86_64/mpi.h:745:21: **note**: in expansion of macro ‘OMPI_PREDEFINED_GLOBAL’
 **#define MPI_OP_NULL OMPI_PREDEFINED_GLOBAL(MPI_Op, ompi_mpi_op_null)**
                     
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:66:24: **note**: in expansion of macro ‘MPI_OP_NULL’
 **MPI::Op::Op() : mpi_op(MPI_OP_NULL) { }**
                        
In file included from MpiDatatype.h:24:0,
                 from MpiData.h:13,
                 from MpiData.cpp:1:
MpiOp.h:21:7: **note**: constexpr MPI_Op::MPI_Op()
 **class MPI_Op {};**
       
MpiOp.h:21:7: **note**:   candidate expects 0 arguments, 1 provided
MpiOp.h:21:7: **note**: constexpr MPI_Op::MPI_Op(const MPI_Op&)
MpiOp.h:21:7: **note**:   no known conversion for argument 1 from ‘void*’ to ‘const MPI_Op&’
MpiOp.h:21:7: **note**: constexpr MPI_Op::MPI_Op(MPI_Op&&)
MpiOp.h:21:7: **note**:   no known conversion for argument 1 from ‘void*’ to ‘MPI_Op&&’
In file included from /usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/mpicxx.h:277:0,
                 from /usr/include/openmpi3-x86_64/mpi.h:2684,
                 from MpiCommunicator.h:79,
                 from MpiData.h:61,
                 from MpiData.cpp:1:
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/op_inln.h: In member function ‘bool MPI::Op::operator==(const MPI::Op&)’:
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:92:63: **error**: no match for ‘operator==’ (operand types are ‘MPI_Op’ and ‘const MPI_Op’)
 **MPI::Op::operator== (const MPI::Op &a) { return (bool)(mpi_op == a.mpi_op); }**
                                                               
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/op_inln.h: In member function ‘virtual void MPI::Op::Init(void (*)(const void*, void*, int, const MPI::Datatype&), bool)’:
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:121:46: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Wpedantic]
     **(void)MPI_Op_create((MPI_User_function*) ompi_mpi_cxx_op_intercept,**
                                              
/usr/include/openmpi3-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:123:59: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Wpedantic]
     **ompi_op_set_cxx_callback(mpi_op, (MPI_User_function*) func);**
                                                           
make[6]: *** [MpiData.o] Error 1

I've also tried compiling with mpich-3.0, mpich-3.2, mvapich2-2.2, mvapich2-2.0, and each time get the same error.
Can this be fixed?

**Comment by seanmarks** [comment]
Thanks for bringing this to my attention: it was an issue with MPI detection and ensuring that the correct preprocessor macros were defined.
